import type { MouseEventHandler } from 'react';

export type sizeTypes = 'l' | 'm' | 's' | 'xs';

export type IconProps = {
  type: keyof typeof IconTypes;
  size?: sizeTypes;
  onClick?: MouseEventHandler | undefined;
  width?: number;
  height?: number;
  className?: string;
  color?: string;
};

export const IconTypes = {
  user: 'User',
  settings: 'Settings',
  sideLeft: 'PanelLeft',
  sideBottom: 'PanelBottom',
  sideRight: 'PanelRight',
  connection: 'Cable',
  lock: 'Lock',
  lockOpen: 'LockOpen',
  database: 'Database',
  refresh: 'RotateCcw',
  search: 'Search',
  sql: 'FileBraces',
  chevronDown: 'ChevronDown',
  chevronRight: 'ChevronRight',
  chevronLeft: 'ChevronLeft',
  chevronUp: 'ChevronUp',
  arrowDown: 'ArrowDown',
  arrowRight: 'ArrowRight',
  arrowLeft: 'ArrowLeft',
  arrowUp: 'ArrowUp',
  columnToken: 'columnToken',
  grid: 'Grid3x3',
  gridBlue: 'Grid3x3',
  filter: 'Funnel',
  sort: 'ArrowDownWideNarrow',
  code: 'Code',
  export: 'FileUp',
  import: 'FileDown',
  close: 'X',
  databaseOutline: 'Database',
  sortBlue: 'sortBlue',
  check: 'Check',
  stop: 'Ban',
  mines: 'Minus',
  plus: 'Plus',
  structure: 'Grid3x3',
  structureBlue: 'Grid3x3',
  delete: 'Trash',
  pen: 'PenLine',
  play: 'Play',
  copy: 'Copy',
  ellipsisVertical: 'EllipsisVertical',
  save: 'Save',
  wand_sparkles: 'WandSparkles',
  pickaxe: 'Pickaxe',
  light: 'Sun',
  dark: 'Moon',
  sheet: 'Sheet',
  databaseZap: 'DatabaseZap',
  theme: 'Palette',
  shortcuts: 'SquareSlash',
  update: 'Download',
  about: 'Info',
  externalLink: 'ExternalLink',
  postgresql: 'postgresql',
  sqlite: 'sqlite',
  mysql: 'mysql',
  mariadb: 'mariadb',
  supabase: 'supabase',
  neon: 'neon',
  alloydb: 'alloydb',
  timescaledb: 'timescaledb',
  amazon_rds: 'amazon_rds',
  amazon_aurora: 'amazon_aurora',
  google_cloud_sql: 'google_cloud_sql',
  azure: 'azure',
  percona: 'percona',
  heatwave: 'heatwave',
  rds_postgresql: 'amazon_rds',
  aurora_postgresql: 'amazon_aurora',
  cloudsql_postgresql: 'google_cloud_sql',
  azure_postgresql: 'azure',
  rds_mysql: 'amazon_rds',
  aurora_mysql: 'amazon_aurora',
  cloudsql_mysql: 'google_cloud_sql',
  azure_mysql: 'azure',
  network: 'Network',
  layout: 'LayoutGrid',
  fit: 'Maximize2',
  send: 'Send',
  at: 'AtSign',
  history: 'RotateCcwClock',
  bot: 'Bot',
  message: 'MessageSquare',
  pause: 'Pause',
  key: 'KeyRound',
  undo: 'Undo2',
  sparkles: 'Sparkles',
  calendar: 'Calendar',
  clock: 'Clock'
};
