# Base layer
FROM node:20-alpine

ENV NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}

# Set the working directory 
WORKDIR /app

# Copy all files 
COPY . .

# Install pnpm
RUN npm i -g pnpm

# Install 
RUN pnpm install

CMD ["pnpm", "next", "dev"]