# Base layer
FROM node:20-alpine

ENV VITE_PUBLIC_SERVER_URL=${VITE_PUBLIC_SERVER_URL}
ENV VITE_VERSION=${VITE_VERSION}
ENV NODE_ENV=${NODE_ENV}

# Set the working directory 
WORKDIR /app

# Copy all files 
COPY . .

# Install 
RUN npm install

CMD ["npm", "run", "dev"]