run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  allow-parallel-runners: true
  allow-serial-runners: true

issues:
  exclude-dirs:
    - test

linters:
  enable:
    - testifylint
    - unconvert
    - govet