FROM golang:1.22-alpine

WORKDIR /back

COPY . .

ENV CGO_ENABLED=1

RUN apk add --no-cache gcc musl-dev

RUN go install github.com/cosmtrek/air@latest

RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]