FROM golang:1.25-alpine

ENV APP_PORT=${APP_PORT}
ENV APP_ENV=${APP_ENV}

WORKDIR /back

COPY . .

ENV CGO_ENABLED=1

RUN apk add --no-cache gcc musl-dev

RUN go install github.com/air-verse/air@latest

RUN go mod download

EXPOSE $APP_PORT

CMD ["air", "-c", ".air.toml"]