import AppAppBar from '@/components/AppAppBar';
import AppTheme from '@/components/theme/AppTheme';
import { CssBaseline } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import type { JSX } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider>
          <AppTheme>
            <CssBaseline enableColorScheme />
            <AppAppBar />
            {children}
          </AppTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
