import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DBO",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
