"use client";

import ThemeProvider from "@/core/theme";
import { CssBaseline } from "@mui/material";
import { Viewport } from "next";
import React from "react";
import { AppConfig } from "../AppConfig";

// export const metadata: Metadata = {
//   title: "DBO",
//   description: "Generated by create next app",
// };

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={AppConfig.locale} dir={AppConfig.direction}>
      <body>
        <CssBaseline />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
