"use client";

import ThemeProvider from "@/core/theme";
import { AppConfig } from "@/core/utils";
import { Providers } from "@/redux/provider";
import { CssBaseline } from "@mui/material";
import { Metadata, Viewport } from "next";
import React, { useEffect } from "react";

export const metadata: Metadata = {
  title: "DBO",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register("/sw.js").then(
        (registration) => {
          console.log(
            "Service Worker registration successful with scope: ",
            registration.scope,
          );
        },
        (err) => {
          console.log("Service Worker registration failed: ", err);
        },
      );
    }
  }, []);

  return (
    <html lang={AppConfig.locale} dir={AppConfig.direction}>
      <body>
        <CssBaseline />
        <Providers>
          <ThemeProvider>{children}</ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
