'use client';

import ThemeProvider from '@/core/theme';
import { CssBaseline } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Viewport } from 'next';
import React from 'react';
import { appConfig } from '../appConfig';

// export const metadata: Metadata = {
//   title: "DBO",
//   description: "Generated by create next app",
// };

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={appConfig.locale} dir={appConfig.direction}>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <CssBaseline />
          <ThemeProvider>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
